- name: tasklevel variables
  hosts: all 
  become: true
  vars:
    - course: DevOps 
    - trainer: siva kumar  
    - duration: 90 days
  gather_facts: yes
  tasks:
    - name: tasklevel variables
      vars:
        course: ansible 
        duration: 10 days 
        trainer: nagesh 
      ansible.builtin.debug:
        msg: "here learning {course}  with in {duration } and trinner is {trainer}"

    - name: play level 
      ansible.builtin.service:
       msg: "here learning {course}  with in {duration } and trinner is {trainer}"
