- name: tasklevel variables
  hosts: all 
  become: true
  vars:
     course: DevOps 
     trainer: siva kumar  
     duration: 90 days
  gather_facts: yes
  tasks:
    - name: play  variables
      vars:
        course: ansible 
        duration: 10 days 
        trainer: nagesh 
      ansible.builtin.debug:
        msg: "here learning {{course}}  with in {{duration }} and trinner is {{trainer}}"

    - name: local level 
      ansible.builtin.debug:
       msg: "here learning {{course}}  with in {{duration }} and trinner is {{trainer}}"
