- name: accessing variables from inverntary file
  hosts: localhost
  become: yes
  gather_facts: true
  tasks:
    - name: accessing the inverntary file variables
      ansible.builtin.debug:
        msg: "hi we are learing {{courese}} with in {{duration}} by trainer {{trainer}}"
