- name: access all types of variables
  hosts: localhost
  # vars:
  # - colour: "task level blue "
  # - paper: "white "
  # vars_prompt:
  #   - name: colour
  #     prompt: enter the colour from the prompt 
  #     private: false 
  #   - name: paper
  #     prompt: please enter the paper name 
  #     private: false
  vars_files:
    - vars.yaml
  tasks:
    # - name: playing paly level variables 
    #   ansible.builtin.debug: 
    #   vars:
    #   - colour: "green"
    #   - paper: "white "
    #     msg: "hi we have colour {{colour}} and paper {{paper}}"
    
    #  - name: playing task level variables 
    #    ansible.builtin.debug:
    #      msg:  "hi we have colour {{colour}} and paper {{paper}}"

     - name: form the inventory file 
       ansible.builtin.debug:
        msg: "hi we are learing {{courese}} with in {{duration}}"
        


# 0 -> Arguments 4 -> prompt level  3-> play level 1 -> task level 2-> vars_files 5-> inventory files 7 -> role level 




