- name: argments variables
  hosts: localhost
  become: yes 
  gather_facts: true 
  tasks:
    - name: access the variables as a arguments by uing -e 
      ansible.builtin.debug:
        msg: "hi we are going to {{place}} on {{day}}"

       # ansible-playbook -i inventory.ini  -e ansible_user=ec2-user -e ansible_password=DevOps321 09-vars-arguments.yaml -e "place=tirupati" -e "day=tomorrow"
