- name: Check the user is exited or not 
  hosts: web 
  become: yes 
  gather_facts: true 
  tasks:
    - name: eheck the user 
      ansible.builtin.command: id expense 
      register: USER_EXp
      ignore_errors: true 

    - name: print user info 
      ansible.builtin.debug:
        msg: "user info is :{{USER_EXp}}"

    - name: print Hello 
      ansible.builtin.debug:
        msg: "hello "