- name: default value 
  hosts: localhost 
  become: yes
  gather_facts: true 
  tasks:
   - name: default vlues 
     ansible.builtin.debug:
      msg: "hi we are learning {{courese | default('Ansible ') }}"
  
- name: upper case converstion 
  hosts: localhost 
  vars:
    content: hello how are you 
  gather_facts: yes 
  tasks:
    - name: upper case 
      ansible.builtin.debug:
        msg: "{{content | upper }}"

- name: lower case converstion 
  hosts: localhost
  vars:
    content: "HI GOOD ABOUT YOU"
  gather_facts: yes 
  tasks:
    - name: lower case
      ansible.builtin.debug:
        msg: "{{content | lower }}"

- name: remove the duplicates 
  hosts: localhost
  vars: 
    ages: [22, 32, 22, 54, 65, 65, 32]
  gather_facts: yes
  tasks:
    - name: removie duplicates 
      ansible.builtin.debug: 
        msg: "{{ ages | unique }}"
