- name: default value 
  hosts: localhost 
  become: yes
  gather_facts: true 
  tasks:
   - name: default vlues 
     ansible.builtin.debug:
      msg: "hi we are learning {{courese | default('Ansible ') }}"
  